name: Docker Image CI

on:
  push:
    branches: [ "arm" ]
  pull_request:
    branches: [ "arm" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file arm/Dockerfile --tag agent:3.1.0-arm
